### PR TITLE
Fix: Optional serialport not working

### PR DESCRIPTION
**Pull request by nytamin**
This PR fixes an issue causing a crash if the optional serialport dependency is not loaded.

Steps to reproduce:
* `git clone https://github.com/nytamin/oscOptionalSerialPortTest.git`
* `npm install --no-optional` <- _use the `no-optional` to make sure the serialport library isn't loaded_
* `node index.js`

This renders the error:
```
Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.\node_modules\osc\src\platforms\osc-node-serialport.js:13:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

It looks like the `osc-node-serialport-loader.js` file introduced in #147 was never used.

### CODE REVIEW

**Comment by colinbdclark** [comment]
Thanks @nytamin, I appreciate it. Not sure what happened with that fix, but I'm glad you caught it and shared a pull request. I'll take a look as soon as I have some free time and merge it in.

**Comment by nytamin** [comment]
@colinbdclark any chance you've got some time to merge this in?
( #162 is a duplicate of this, so there are more than me who has this issue )

**Comment by colinbdclark** [comment]
Hi @nytamin, thanks for the fix. I've merged it and cut v2.3.2. Open source is hard—life can really get in the way. Apologies for the delay.
